###########
# site.title

title:    'Nigam Shah'
subtitle: ''
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


nav:
- { title: 'Shell',              href: '/terminal.html' }
# - { title: 'Resume',             href: 'https://drive.google.com/file/d/1TQ0-m0O0iCp9C6I3g7_C5Kulih2xYTKA/view?usp=sharing' }


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: resources/css
  style:    expanded

exclude:
- README.md
- LICENSE.md

