###########
# site.title

title:    'Nigam Shah'
subtitle: ''


nav:
- { title: 'About',              href: '/' }
- { title: 'Resume',             href: '/' }


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

